import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://tutorialsninja.com/demo/');
  await page.getByRole('button', { name: '$ Currency  ' }).click();
  await page.getByRole('button', { name: '€Euro' }).click();
  await page.getByRole('link', { name: 'Canon EOS 5D' }).first().click();
  await page.getByRole('button', { name: 'Add to Cart', exact: true }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  //await page.getByRole('button', { name: 'Add to Cart' }).click();
  //await page.locator('#content > div.row > div:nth-child(4) > div > div.button-group > button:nth-child(1) > span').click();
  await page.getByText('Select required!').click();
  await page.getByRole('link', { name: 'Qafox.com' }).click();

  await page.locator('div').filter({ hasText: 'iPhone iPhone is a' }).nth(5).click();
  await page.getByRole('link', { name: 'iPhone' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Qty' }).click();
  await page.getByRole('textbox', { name: 'Qty' }).fill('2');
  await page.getByRole('button', { name: 'Add to Cart', exact: true }).click();
  await page.getByRole('button', { name: 'Add to Cart', exact: true }).click();
  await page.pause();

  await page.getByText('Success: You have added').click();
  await page.getByRole('button', { name: ' 2 item(s) - 193.33€' }).click();
  await page.getByRole('link', { name: ' View Cart' }).click();
  //await page.locator('input[name="quantity[336696]"]').click();
  await page.locator('//*[@id="content"]/form/div/table/tbody/tr/td[4]/div/input').click();
  await page.locator('//*[@id="content"]/form/div/table/tbody/tr/td[4]/div/input').fill('3');
  //await page.locator('input[name="quantity[336696]"]').fill('3');
  await page.getByRole('button').nth(4).click();
  await page.getByText('Eco Tax (-2.00):').click();
  await page.getByRole('cell', { name: '4.71€' }).click();
  await page.getByText('VAT (20%):').click();
  await page.getByRole('cell', { name: '47.55€' }).click();
  await page.getByRole('link', { name: 'Checkout', exact: true }).click();
  await page.getByText('Products marked with *** are').click();
  await page.getByRole('button').nth(5).click();
  await page.getByRole('heading', { name: 'Shopping Cart' }).click();
  await page.locator('#content').getByText('Your shopping cart is empty!').click();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.getByRole('link', { name: 'Laptops & Notebooks', exact: true }).click();
  await page.getByRole('link', { name: 'Show AllLaptops & Notebooks' }).click();
  await page.getByRole('link', { name: 'HP LP3065' }).first().click();
  await page.getByRole('textbox', { name: 'Qty' }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.pause();
  await page.getByText('Success: You have added HP').click();
  await page.getByRole('link', { name: ' Shopping Cart' }).click();
  await page.getByRole('link', { name: 'Use Coupon Code ' }).click();
  await page.getByRole('textbox', { name: 'Enter your coupon here' }).click();
  await page.getByRole('textbox', { name: 'Enter your coupon here' }).fill('ABCD123');
  await page.getByRole('button', { name: 'Apply Coupon' }).click();
  await page.getByText('Warning: Coupon is either').click();
  await page.getByRole('heading', { name: 'Use Gift Certificate ' }).click();
  await page.getByRole('link', { name: 'Use Gift Certificate ' }).click();

  await page.getByRole('textbox', { name: 'Enter your gift certificate' }).click();
  await page.getByRole('textbox', { name: 'Enter your gift certificate' }).fill('AXDFGH123');
  await page.getByRole('button', { name: 'Apply Gift Certificate' }).click();
  await page.getByText('Warning: Gift Certificate is').click();
  await page.getByRole('textbox', { name: 'Enter your gift certificate' }).click();
  await page.getByRole('textbox', { name: 'Enter your gift certificate' }).fill('');
  await page.getByRole('link', { name: 'Use Coupon Code ' }).click();
  await page.getByRole('textbox', { name: 'Enter your coupon here' }).click();
  await page.getByRole('textbox', { name: 'Enter your coupon here' }).fill('');
  await page.getByRole('link', { name: 'Checkout', exact: true }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: '* First Name' }).click();
  await page.getByRole('textbox', { name: '* First Name' }).fill('A');
  await page.getByRole('textbox', { name: '* Last Name' }).click();
  await page.getByRole('textbox', { name: '* Last Name' }).fill('B');
  await page.getByRole('textbox', { name: '* E-Mail' }).click();
  await page.getByRole('textbox', { name: '* E-Mail' }).fill('AB@gmail.com');
  await page.getByRole('textbox', { name: '* Telephone' }).click();
  await page.getByRole('textbox', { name: '* Telephone' }).fill('12345678');
  await page.getByRole('textbox', { name: '* Address' }).click();
  await page.getByRole('textbox', { name: '* Address' }).fill('Address1');
  await page.getByRole('textbox', { name: '* City' }).click();
  await page.getByRole('textbox', { name: '* City' }).fill('City');
  await page.getByRole('textbox', { name: '* Post Code' }).click();
  await page.getByRole('textbox', { name: '* Post Code' }).fill('12345');
  await page.getByLabel('Country').selectOption('223');
  await page.getByLabel('Region / State').selectOption('3613');
  await page.getByRole('textbox', { name: '* Password', exact: true }).click();
  await page.getByRole('textbox', { name: '* Password', exact: true }).fill('P@ssword123');
  await page.getByRole('textbox', { name: '* Password Confirm' }).click();
  await page.getByRole('textbox', { name: '* Password Confirm' }).fill('P@ssword123');
  await page.locator('input[name="agree"]').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('Warning: E-Mail Address is').click();

  await page.getByRole('textbox', { name: '* E-Mail' }).click();
  await page.getByRole('textbox', { name: '* E-Mail' }).fill('qwert@gmail.com');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('Warning: E-Mail Address is').click();
  await page.getByRole('textbox', { name: '* E-Mail' }).click();
  await page.getByRole('textbox', { name: '* E-Mail' }).fill('sashi1234567@gmail.com');
  await page.locator('input[name="agree"]').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('heading', { name: 'Step 3: Delivery Details ' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('heading', { name: 'Step 4: Delivery Method ' }).click();
  await page.locator('textarea[name="comment"]').click();
  await page.locator('textarea[name="comment"]').fill('dasdsa');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('heading', { name: 'Step 6: Confirm Order ' }).click();
  await page.getByRole('button', { name: 'Confirm Order' }).click();
  await page.getByRole('heading', { name: 'Your order has been placed!' }).click();
  await page.getByText('Your order has been successfully processed!').click();
  await page.getByText('You can view your order').click();
  await page.getByRole('link', { name: 'Continue' }).click();
});