import {test, expect} from '@playwright/test';
import {Home} from '../Pages/Home';
import {RegisterAcc} from '../Pages/RegisterAcc.js';


test('Launch Home Page', async ({page}) => {
    const homeobj = new Home(page);
    await homeobj.launchApp();
    await homeobj.changeCurrencyToEuro();

});

test('Register account', async ({page}) => {
    const homeobj = new Home(page);
   const registerobj = new RegisterAcc(page);
   //test.beforeEach()
   await registerobj.registerAccount();
   });


/* test('registeracc', async ({page}) => {
    await page.goto('https://tutorialsninja.com/demo/');
    await page.getByRole('link', { name: 'Laptops & Notebooks', exact: true }).click();
await page.getByRole('link', { name: 'Show AllLaptops & Notebooks' }).click();
await page.getByRole('button', { name: ' Add to Cart' }).first().click();
await page.getByRole('link', { name: ' Checkout' }).click();
await page.getByRole('link', { name: 'Shopping Cart', exact: true }).click();
await page.getByRole('link', { name: 'Qafox.com' }).click();
await page.getByText('Canon EOS 5D').click();
await page.getByRole('button', { name: 'Add to Cart' }).click();
await page.getByText('Select required!').click();
await page.getByRole('link', { name: ' Checkout' }).click();
           await page.getByRole('link', { name: 'Qafox.com' }).click();
    await page.locator('div').filter({ hasText: 'iPhone iPhone is a' }).nth(5).click();
    await page.getByRole('heading', { name: 'iPhone' }).click();
    await page.getByRole('link', { name: 'iPhone' }).nth(2).click();
    await page.getByRole('textbox', { name: 'Qty' }).click();
    await page.getByRole('textbox', { name: 'Qty' }).fill('2');
    await page.getByRole('button', { name: 'Add to Cart', exact: true }).click();
    await page.getByRole('button', { name: 'Add to Cart', exact: true }).click();
    await page.getByText('Success: You have added').click();
    await page.expect(page.getByRole('button', { name: ' 4 item(s) - 386.65€' })).toBeVisible();
    await page.getByRole('button', { name: ' 4 item(s) - 386.65€' }).click();
    await page.getByText('iPhone x4 386.65€ Sub-Total').click();
    await page.getByRole('button', { name: ' 4 item(s) - 386.65€' }).click();
    await page.getByRole('link', { name: ' View Cart' }).click();
    await page.locator('input[name="quantity[334153]"]').click();
    await page.locator('input[name="quantity[334153]"]').fill('3');
    await page.getByRole('button').nth(4).click();
    await page.getByText('Eco Tax (-2.00):').click();
    await page.getByRole('cell', { name: '4.71€' }).click();
    await page.getByText('VAT (20%):').click();
    await page.getByRole('cell', { name: '47.55€' }).click();
    await page.getByRole('link', { name: 'Checkout', exact: true }).click();
    await page.getByText('Products marked with *** are').click();
    await page.getByRole('button').nth(5).click();
    await page.getByRole('link', { name: 'Laptops & Notebooks', exact: true }).click();
    await page.getByRole('link', { name: 'Show AllLaptops & Notebooks' }).click();
    await page.locator('div').filter({ hasText: 'HP LP3065 Stop your co-' }).nth(5).click();
    await page.getByText('HP LP3065', { exact: true }).click();
    await page.expect(page.getByRole('textbox', { name: 'Qty' })).toBeVisible();
    await page.getByRole('textbox', { name: 'Qty' }).click();
    await page.getByRole('button', { name: 'Add to Cart' }).click();
    await page.getByText('Success: You have added HP').click();
    await page.locator('#top-links').click();
    await page.getByRole('link', { name: ' Shopping Cart' }).click();
    await page.locator('body').click();
    await page.getByRole('link', { name: 'Use Coupon Code ' }).click();
    await page.getByRole('textbox', { name: 'Enter your coupon here' }).click();
    await page.getByRole('textbox', { name: 'Enter your coupon here' }).fill('ABCD123');
    await page.getByRole('button', { name: 'Apply Coupon' }).click();
    await page.getByText('Warning: Coupon is either').click();
    await page.getByRole('heading', { name: 'Use Gift Certificate ' }).click();
    await page.getByRole('link', { name: 'Use Gift Certificate ' }).click();
    await page.getByRole('textbox', { name: 'Enter your gift certificate' }).click();
    await page.getByRole('textbox', { name: 'Enter your gift certificate' }).fill('AXDFGH123');
    await page.getByRole('button', { name: 'Apply Gift Certificate' }).click();
    await page.getByText('Warning: Gift Certificate is').click();
    await page.getByRole('textbox', { name: 'Enter your gift certificate' }).click();
    await page.getByRole('textbox', { name: 'Enter your gift certificate' }).click();
    await page.getByRole('textbox', { name: 'Enter your gift certificate' }).fill('');
    await page.getByRole('link', { name: 'Use Coupon Code ' }).click();
    await page.getByRole('textbox', { name: 'Enter your coupon here' }).click();
    await page.getByRole('textbox', { name: 'Enter your coupon here' }).fill('');
    await page.getByRole('link', { name: 'Checkout', exact: true }).click();
    await page.locator('body').click();
    await page.getByText('Shopping Cart Checkout Checkout Step 1: Checkout Options New Customer Checkout').click();
    await page.getByRole('heading', { name: 'Checkout', exact: true }).click();
    await page.getByRole('heading', { name: 'Step 1: Checkout Options ' }).click();
    await page.getByText('New Customer Checkout Options').click();
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.getByRole('heading', { name: 'Step 2: Account & Billing' }).click();
    await page.locator('#collapse-payment-address > .panel-body').click();
    await page.getByText('Your Personal Details').click();
    await page.getByRole('textbox', { name: '* First Name' }).click();
    await page.getByRole('textbox', { name: '* First Name' }).fill('Sashi');
    await page.getByRole('textbox', { name: '* Last Name' }).click();
    await page.getByRole('textbox', { name: '* Last Name' }).fill('W');
    await page.getByRole('textbox', { name: '* E-Mail' }).click();
    await page.getByRole('textbox', { name: '* E-Mail' }).fill('wunnava@sashi@gmail.com');
    await page.getByRole('textbox', { name: '* Telephone' }).click();
    await page.getByRole('textbox', { name: '* Telephone' }).fill('1111111111');
    await page.getByRole('textbox', { name: '* Password', exact: true }).dblclick();
    await page.getByRole('textbox', { name: '* Password', exact: true }).fill('P@ssword123');
    await page.getByRole('textbox', { name: '* Password Confirm' }).click();
    await page.getByRole('textbox', { name: '* Password Confirm' }).fill('P@ssword123');
    await page.getByText('Your Address').click();
    await page.getByRole('textbox', { name: '* Address' }).click();
    await page.getByRole('textbox', { name: '* Address' }).fill('Address1');
    await page.getByRole('textbox', { name: '* City' }).click();
    await page.getByRole('textbox', { name: '* City' }).fill('City1');
    await page.getByRole('textbox', { name: '* Post Code' }).click();
    await page.getByRole('textbox', { name: '* Post Code' }).fill('11111');
    await page.getByLabel('Country').selectOption('223');
    await page.getByLabel('Region / State').selectOption('3673');
    await page.locator('input[name="agree"]').check();
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.getByRole('heading', { name: 'Step 3: Delivery Details' }).click();
    await page.getByRole('heading', { name: 'Step 3: Delivery Details' }).click();
    await page.getByRole('heading', { name: 'Step 4: Delivery Method ' }).click();
    await page.locator('textarea[name="comment"]').click();
    await page.locator('textarea[name="comment"]').fill('comments added');
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.locator('div').filter({ hasText: 'Step 5: Payment Method' }).nth(5).click();
    await page.getByRole('checkbox').check();
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.getByRole('heading', { name: 'Step 6: Confirm Order ' }).click();
    await page.locator('#collapse-checkout-confirm > .panel-body').click();
    await page.getByRole('button', { name: 'Confirm Order' }).click();
    await page.getByText('Your order has been placed!Your order has been successfully processed!You can').click();
    await page.getByText('Shopping Cart Checkout Success').click();
    await page.getByRole('link', { name: 'Continue' }).click();
    await page.getByRole('link', { name: 'Contact Us' }).click();
    await page.getByRole('textbox', { name: '* Enquiry' }).click();
    await page.getByRole('textbox', { name: '* Enquiry' }).fill('when is the shipping date for my product');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('link', { name: 'Continue' }).click();
}); */