import {test, expect} from '@playwright/test';
export class Home {
    constructor(page) {
        this.page = page;
    }

    async registerAccount() {
        //await this.page.goto('await page.goto('https://tutorialsninja.com/demo/'););
        //await this.page.getByRole('link', { name: 'My Account' }).click();
        //    await this.page.getByRole('link', { name: 'Register' }).click();
        
 await this.page.goto('https://tutorialsninja.com/demo/');
 await this.page.getByRole('button', { name: '$ Currency  ' }).click();
 await this.page.getByRole('button', { name: '€Euro' }).click();
 // add to cart
 await this.page.locator('div').filter({ hasText: 'Canon EOS 5D Canon\'s press' }).nth(4).click();
 await this.page.getByText('Canon\'s press material for').click();
 await this.page.getByText('Canon EOS 5D').click();
 await this.page.locator('body').click();
 await this.page.getByRole('button', { name: '×' }).click();
 await this.page.getByRole('button', { name: 'Add to Cart' }).click();
 await this.page.getByText('Select required!').click();
 //go to home
 await this.page.getByRole('link', { name: 'Qafox.com' }).click();
 //add to cart
 await this.page.locator('div').filter({ hasText: 'iPhone iPhone is a' }).nth(5).click();
 await this.page.getByRole('heading', { name: 'iPhone' }).click();
 await this.page.getByRole('link', { name: 'iPhone' }).nth(2).click();
 await this.page.getByRole('textbox', { name: 'Qty' }).click();
 await this.page.getByRole('textbox', { name: 'Qty' }).fill('2');
 await this.page.getByRole('button', { name: 'Add to Cart', exact: true }).click();
 await this.page.getByRole('button', { name: 'Add to Cart', exact: true }).click();
 await this.page.getByText('Success: You have added').click();
 await this.page.expect(page.getByRole('button', { name: ' 4 item(s) - 386.65€' })).toBeVisible();
 await this.page.getByRole('button', { name: ' 4 item(s) - 386.65€' }).click();
 await this.page.getByText('iPhone x4 386.65€ Sub-Total').click();
 await this.page.getByRole('button', { name: ' 4 item(s) - 386.65€' }).click();
 await this.page.getByRole('link', { name: ' View Cart' }).click();
 await this.page.locator('input[name="quantity[334153]"]').click();
 await this.page.locator('input[name="quantity[334153]"]').fill('3');
 await this.page.getByRole('button').nth(4).click();
 await this.page.getByText('Eco Tax (-2.00):').click();
 await this.page.getByRole('cell', { name: '4.71€' }).click();
 await this.page.getByText('VAT (20%):').click();
 await this.page.getByRole('cell', { name: '47.55€' }).click();
 await this.page.getByRole('link', { name: 'Checkout', exact: true }).click();
 await this.page.getByText('Products marked with *** are').click();
 await this.page.getByRole('button').nth(5).click();
 await this.page.getByRole('link', { name: 'Laptops & Notebooks', exact: true }).click();
 await this.page.getByRole('link', { name: 'Show AllLaptops & Notebooks' }).click();
 await this.page.locator('div').filter({ hasText: 'HP LP3065 Stop your co-' }).nth(5).click();
 await this.page.getByText('HP LP3065', { exact: true }).click();
 await this.page.expect(page.getByRole('textbox', { name: 'Qty' })).toBeVisible();
 await this.page.getByRole('textbox', { name: 'Qty' }).click();
 await this.page.getByRole('button', { name: 'Add to Cart' }).click();
 await this.page.getByText('Success: You have added HP').click();
 await this.page.locator('#top-links').click();
 await this.page.getByRole('link', { name: ' Shopping Cart' }).click();
 await this.page.locator('body').click();
 await this.page.getByRole('link', { name: 'Use Coupon Code ' }).click();
 await this.page.getByRole('textbox', { name: 'Enter your coupon here' }).click();
 await this.page.getByRole('textbox', { name: 'Enter your coupon here' }).fill('ABCD123');
 await this.page.getByRole('button', { name: 'Apply Coupon' }).click();
 await this.page.getByText('Warning: Coupon is either').click();
 await this.page.getByRole('heading', { name: 'Use Gift Certificate ' }).click();
 await this.page.getByRole('link', { name: 'Use Gift Certificate ' }).click();
 await this.page.getByRole('textbox', { name: 'Enter your gift certificate' }).click();
 await this.page.getByRole('textbox', { name: 'Enter your gift certificate' }).fill('AXDFGH123');
 await this.page.getByRole('button', { name: 'Apply Gift Certificate' }).click();
 await this.page.getByText('Warning: Gift Certificate is').click();
 await this.page.getByRole('textbox', { name: 'Enter your gift certificate' }).click();
 await this.page.getByRole('textbox', { name: 'Enter your gift certificate' }).click();
 await this.page.getByRole('textbox', { name: 'Enter your gift certificate' }).fill('');
 await this.page.getByRole('link', { name: 'Use Coupon Code ' }).click();
 await this.page.getByRole('textbox', { name: 'Enter your coupon here' }).click();
 await this.page.getByRole('textbox', { name: 'Enter your coupon here' }).fill('');
 await this.page.getByRole('link', { name: 'Checkout', exact: true }).click();
 await this.page.locator('body').click();
 await this.page.getByText('Shopping Cart Checkout Checkout Step 1: Checkout Options New Customer Checkout').click();
 await this.page.getByRole('heading', { name: 'Checkout', exact: true }).click();
 await this.page.getByRole('heading', { name: 'Step 1: Checkout Options ' }).click();
 await this.page.getByText('New Customer Checkout Options').click();
 await this.page.getByRole('button', { name: 'Continue' }).click();
 await this.page.getByRole('heading', { name: 'Step 2: Account & Billing' }).click();
 await this.page.locator('#collapse-payment-address > .panel-body').click();
 await this.page.getByText('Your Personal Details').click();
 await this.page.getByRole('textbox', { name: '* First Name' }).click();
 await this.page.getByRole('textbox', { name: '* First Name' }).fill('Sashi');
 await this.page.getByRole('textbox', { name: '* Last Name' }).click();
 await this.page.getByRole('textbox', { name: '* Last Name' }).fill('W');
 await this.page.getByRole('textbox', { name: '* E-Mail' }).click();
 await this.page.getByRole('textbox', { name: '* E-Mail' }).fill('wunnava@sashi@gmail.com');
 await this.page.getByRole('textbox', { name: '* Telephone' }).click();
 await this.page.getByRole('textbox', { name: '* Telephone' }).fill('1111111111');
 await this.page.getByRole('textbox', { name: '* Password', exact: true }).dblclick();
 await this.page.getByRole('textbox', { name: '* Password', exact: true }).fill('P@ssword123');
 await this.page.getByRole('textbox', { name: '* Password Confirm' }).click();
 await this.page.getByRole('textbox', { name: '* Password Confirm' }).fill('P@ssword123');
 await this.page.getByText('Your Address').click();
 await this.page.getByRole('textbox', { name: '* Address' }).click();
 await this.page.getByRole('textbox', { name: '* Address' }).fill('Address1');
 await this.page.getByRole('textbox', { name: '* City' }).click();
 await this.page.getByRole('textbox', { name: '* City' }).fill('City1');
 await this.page.getByRole('textbox', { name: '* Post Code' }).click();
 await this.page.getByRole('textbox', { name: '* Post Code' }).fill('11111');
 await this.page.getByLabel('Country').selectOption('223');
 await this.page.getByLabel('Region / State').selectOption('3673');
 await this.page.locator('input[name="agree"]').check();
 await this.page.getByRole('button', { name: 'Continue' }).click();
 await this.page.getByRole('heading', { name: 'Step 3: Delivery Details' }).click();
 await this.page.getByRole('heading', { name: 'Step 3: Delivery Details' }).click();
 await this.page.getByRole('heading', { name: 'Step 4: Delivery Method ' }).click();
 await this.page.locator('textarea[name="comment"]').click();
 await this.page.locator('textarea[name="comment"]').fill('comments added');
 await this.page.getByRole('button', { name: 'Continue' }).click();
 await this.page.locator('div').filter({ hasText: 'Step 5: Payment Method' }).nth(5).click();
 await this.page.getByRole('checkbox').check();
 await this.page.getByRole('button', { name: 'Continue' }).click();
 await this.page.getByRole('heading', { name: 'Step 6: Confirm Order ' }).click();
 await this.page.locator('#collapse-checkout-confirm > .panel-body').click();
 await this.page.getByRole('button', { name: 'Confirm Order' }).click();
 await this.page.getByText('Your order has been placed!Your order has been successfully processed!You can').click();
 await this.page.getByText('Shopping Cart Checkout Success').click();
 await this.page.getByRole('link', { name: 'Continue' }).click();
 await this.page.getByRole('link', { name: 'Contact Us' }).click();
 await this.page.getByRole('textbox', { name: '* Enquiry' }).click();
 await this.page.getByRole('textbox', { name: '* Enquiry' }).fill('when is the shipping date for my product');
 await this.page.getByRole('button', { name: 'Submit' }).click();
 await this.page.getByRole('link', { name: 'Continue' }).click();
}
}